version: "3.7"
services:
  openclaw_ts:
    image: tailscale/tailscale:latest
    container_name: openclaw_ts
    hostname: openclaw
    environment:
      - TS_AUTHKEY=tskey-client-xxxxxxxxxxxxxx?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --reset
      - TS_SERVE_CONFIG=/config/openclaw.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=false
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /docs/openclaw/tailscale/config:/config
      - /docs/openclaw/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    
  openclaw:
    build: .
    image: openclaw:local-with-go
    container_name: openclaw
    network_mode: service:openclaw_ts
    depends_on:
      - openclaw_ts
    volumes:
      - /docs/openclaw/data:/home/node/.openclaw
    environment:
      - OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}
      - OPENCLAW_GATEWAY_BIND=lan
      - OPENCLAW_GATEWAY_CONTROL_UI_ALLOWED_ORIGINS=https://openclaw.burro-iguana.ts.net
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    tty: true
    stdin_open: true
    restart: unless-stopped
