version: "3"

services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9001:9000"
    volumes:
      - /mylab/sonarqube/conf:/opt/sonarqube/conf
      - /mylab/sonarqube/data:/opt/sonarqube/data
      - /mylab/sonarqube/extensions:/opt/sonarqube/extensions
      - /mylab/sonarqube/logs:/opt/sonarqube/logs
      - /mylab/sonarqube/temp:/opt/sonarqube/temp

  sonar_db:
    container_name: sonarqube_db
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - /mylab/sonarqube_db/postgresql:/var/lib/postgresql
      - /mylab/sonarqube_db/postgresql/data:/var/lib/postgresql/data