version: "3.7"
services:
  jellyfin_ts:
    image: tailscale/tailscale:latest
    container_name: jellyfin_ts
    hostname: jellyfin
    environment:
      - TS_AUTHKEY=tskey-client-xxxxxxxxxxxxxx?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --reset
      - TS_SERVE_CONFIG=/config/jellyfin.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /media/jellyfin/tailscale/config:/config
      - /media/jellyfin/tailscale/jellyfin_ts/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    healthcheck:
      test: tailscale status --peers=false --json | grep -q 'Online...true'
    
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - /media/jellyfin/config:/config
      - /media/jellyfin/cache:/cache
      - /media:/media
    network_mode: service:jellyfin_ts
    depends_on:
      - jellyfin_ts
    restart: unless-stopped
 