version: "3.7"
services:
  nextcloud_ts:
    image: tailscale/tailscale:latest
    container_name: nextcloud_ts
    hostname: nextcloud
    environment:
      - TS_AUTHKEY=tskey-client-k5vpXN26VR11CNTRL-wgRs5T58Q8dQQpBqxHgP7dULcczVyiou?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --reset
      - TS_SERVE_CONFIG=/config/nextcloud.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /docs/nextcloud/tailscale/config:/config
      - /docs/nextcloud/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    healthcheck:
      test: tailscale status --peers=false --json | grep -q 'Online...true'
    
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    network_mode: service:nextcloud_ts
    depends_on:
      - nextcloud_ts
      - nextcloud_db
      - nexcloud_redis
    volumes:
      - /docs/nextcloud:/var/www/html
      - /docs/nextcloud/custom_apps:/var/www/html/custom_apps
      - /docs/nextcloud/config:/var/www/html/config
      - /docs/nextcloud/data:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=tvmas234asd_sdf
      - MYSQL_HOST=nextcloud_db
      - REDIS_HOST=nextcloud_redis
    restart: unless-stopped

  nextcloud_db:
    image: mariadb
    container_name: nextcloud_db
    restart: unless-stopped
    network_mode: service:nextcloud_ts
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW    
    volumes:
      - /docs/nextcloud/db:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=tvmas234asd_sdf
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nexcloud_redis:
    image: redis:alpine
    network_mode: service:nextcloud_ts
    container_name: redis
    healthcheck:
      test: redis-cli ping || exit 1
